use_frameworks!

target 'MyFirstCocoaPodsLib_Example' do
  pod 'MyFirstCocoaPodsLib', :path => '../'

  target 'MyFirstCocoaPodsLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
